[project]
name = "vector-processor"
dynamic = ["version"]
requires-python = ">=3.13,<3.14"
dependencies = [
    "api",
    "core",
    "grpcio>=1.80.0",
    "pillow>=12.2.0",
    "pydantic-settings>=2.13.1",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.5.4",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
api = { workspace = true }
core = { workspace = true }

torch = [
  { index = "pytorch-cpu" },
]

torchvision = [
  { index = "pytorch-cpu" },
]

[tool.setuptools.packages.find]
where = ["."]

[dependency-groups]
dev = [
    "grpcio-reflection>=1.80.0",
    "pytest>=9.0.3",
]
